name: Otomatik Muzik Indirici
on: [workflow_dispatch]

# GITHUB_TOKEN'a repoya yazma izni veriyoruz, böylece workflow içinden git push yapabilirsiniz
permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Sarkilari Sunucuya Cek
      run: |
        curl -L "https://archive.org" -o yerliplaka.mp3
        curl -L "https://archive.org" -o holokost.mp3
        curl -L "https://archive.org" -o neyimvarkimim.mp3
        curl -L "https://archive.org" -o medcezir.mp3
        curl -L "https://archive.org" -o farkvar.mp3

    - name: Sarkilari Depoya Yukle
      run: |
        git config --global user.name "MuzikBot"
        git config --global user.email "bot@github.com"
        git add *.mp3
        git commit -m "Sarkilar yuklendi" || exit 0
        git push
